parameters:

services:
    # Default configuration for services in *this* file
    _defaults:
        autowire: true      # Automatically injects dependencies in your services.
        autoconfigure: true # Automatically registers your services as commands, event subscribers, etc.

    # makes classes in src/ available to be used as services
    # this creates a service per class whose id is the fully-qualified class name
    App\:
        resource: '../src/'
        exclude:
            - '../src/DependencyInjection/'
            - '../src/Entity/'
            - '../src/Kernel.php'

    # Explicit service definition for the default messenger bus, make it public
    Symfony\Component\Messenger\MessageBusInterface:
        class: Symfony\Component\Messenger\MessageBus
        public: true
        arguments:
            - '@messenger.senders_locator'
            - '@messenger.receiver_locator'

    # Register the DispatchBookFetchJobCommand class as a service
    App\Command\DispatchBookFetchJobCommand:
        arguments:
            $bus: '@messenger.default_bus'  # Automatically inject the message bus service

    # Register the BookFetchJobHandler as a message handler
    App\MessageHandler\BookFetchJobHandler:
        tags: ['messenger.message_handler']  # Tells Symfony this is a handler for Messenger messages

    # Optional: Explicitly define other messenger buses if needed
    # Symfony\Component\Messenger\MessageBusInterface: '@messenger.bus.some_other_bus'

    # You can add additional service definitions if needed.



